# ============================================================
# Hollis Identity Service — Multi-stage Docker build
# Stage 1: deps   — install production dependencies
# Stage 2: build  — compile TypeScript
# Stage 3: runner — lean production image
# ============================================================

# ---- Stage 1: deps ----
FROM node:20-alpine AS deps
WORKDIR /workspace/hollis-identity
# Match the dev npm (11.x): the lockfile is generated by npm 11, which treats
# @prisma/studio-core's react deps as optional peers. node:20-alpine ships npm
# 10.8.2, whose stricter `npm ci` sync check rejects that lockfile.
RUN npm i -g npm@11.10.0
COPY package.json package-lock.json* ./
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm ci --omit=dev

# ---- Stage 2: build ----
FROM node:20-alpine AS build
WORKDIR /workspace/hollis-identity
RUN npm i -g npm@11.10.0
COPY package.json package-lock.json* ./
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm ci
COPY tsconfig.json ./
COPY src/ ./src/
COPY prisma/ ./prisma/
RUN npm run prisma:generate
# tsconfig uses moduleResolution "bundler" (extensionless imports), so raw tsc
# output can't run under Node ESM. Bundle the app + generated Prisma client into
# a single ESM file; keep node_modules (Prisma/pg/express) external. Identity uses
# the PrismaPg driver adapter (no native engine binary), so this bundles cleanly.
RUN npx --yes esbuild@0.25.0 src/index.ts --bundle --platform=node --format=esm --packages=external --outfile=dist/index.js

# ---- Stage 3: runner ----
FROM node:20-alpine AS runner
WORKDIR /workspace/hollis-identity
ENV NODE_ENV=production

COPY --from=deps /workspace/hollis-identity/node_modules ./node_modules
COPY --from=build /workspace/hollis-identity/dist ./dist
COPY --from=build /workspace/hollis-identity/prisma ./prisma
COPY prisma.config.ts ./
COPY package.json ./

EXPOSE 4001

# esbuild emits a single bundled ESM file at dist/index.js.
CMD ["node", "dist/index.js"]
