# ============================================================
# Hollis Identity Service — Multi-stage Docker build
# Stage 1: deps   — install production dependencies
# Stage 2: build  — compile TypeScript
# Stage 3: runner — lean non-root production image
#
# Base image: node:22-alpine, SHA-pinned for supply-chain integrity. Node 20
# went end-of-life (2026-04-30) and its alpine base stopped receiving openssl
# patches, which is how the live image ended up carrying CRITICAL openssl
# advisories. 22 is the Active LTS line and matches
# hollis-health-app/server/Dockerfile; hollis-workouts/server/Dockerfile is
# still on 20 and needs the same bump (not this repo's to make).
#
# All three stages pin the SAME digest — the multi-arch manifest LIST for
# node:22-alpine, not a per-architecture manifest, so the image still builds on
# arm64 (local) and amd64 (CI, which is what Fargate runs).
#
# Pinned 2026-09-20: sha256:b6f26b36c8ff49624cfdac716b8ea1138d606df02586a77d364bb5536a634f85
#
# Re-resolve (the tag moves on every upstream Node patch release). Needs no
# Docker daemon and returns the manifest-list digest rather than a per-arch one:
#   TOKEN=$(curl -sS "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/node:pull" \
#     | python3 -c "import sys,json;print(json.load(sys.stdin)['token'])")
#   curl -sSI -H "Authorization: Bearer $TOKEN" \
#     -H "Accept: application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.list.v2+json" \
#     https://registry-1.docker.io/v2/library/node/manifests/22-alpine | grep -i docker-content-digest
# .github/dependabot.yml now also raises a weekly PR when the digest moves.
# ============================================================

# ---- Stage 1: deps ----
FROM node:25-alpine@sha256:bdf2cca6fe3dabd014ea60163eca3f0f7015fbd5c7ee1b0e9ccb4ced6eb02ef4 AS deps
WORKDIR /workspace/hollis-identity
# Match the dev npm (11.x): the lockfile is generated by npm 11, which treats
# @prisma/studio-core's react deps as optional peers. node:22-alpine ships
# npm 10.x, whose stricter `npm ci` sync check rejects that lockfile.
RUN npm i -g npm@11.10.0
COPY package.json package-lock.json* ./
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm ci --omit=dev

# ---- Stage 2: build ----
FROM node:25-alpine@sha256:bdf2cca6fe3dabd014ea60163eca3f0f7015fbd5c7ee1b0e9ccb4ced6eb02ef4 AS build
WORKDIR /workspace/hollis-identity
RUN npm i -g npm@11.10.0
COPY package.json package-lock.json* ./
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm ci
COPY tsconfig.json ./
COPY src/ ./src/
COPY prisma/ ./prisma/
RUN npm run prisma:generate
# tsconfig uses moduleResolution "bundler" (extensionless imports), so raw tsc
# output can't run under Node ESM. Bundle the app + generated Prisma client into
# a single ESM file; keep node_modules (Prisma/pg/express) external. Identity uses
# the PrismaPg driver adapter (no native engine binary), so this bundles cleanly.
RUN npx --yes esbuild@0.25.0 src/index.ts --bundle --platform=node --format=esm --packages=external --outfile=dist/index.js

# ---- Stage 3: runner ----
FROM node:25-alpine@sha256:bdf2cca6fe3dabd014ea60163eca3f0f7015fbd5c7ee1b0e9ccb4ced6eb02ef4 AS runner
WORKDIR /workspace/hollis-identity
ENV NODE_ENV=production

# openssl: the Prisma SCHEMA engine (used by `prisma migrate deploy` at startup)
# links against it on musl. Installing the package also pulls the patched
# version from the current alpine branch rather than whatever the base carries.
#
# Non-root runtime (uid/gid 1001, matching the Health and Workouts servers).
# HOME must be a directory this user owns: the Prisma CLI writes a version-check
# cache under $HOME, and the default /root is not writable after `USER`.
RUN apk add --no-cache openssl && \
    addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 --ingroup nodejs --home /home/identity identity
ENV HOME=/home/identity

# Everything the runtime reads is owned by the runtime user. node_modules in
# particular must be readable by it — it carries the generated Prisma client
# and the schema-engine binary the startup migration invokes.
COPY --from=deps --chown=identity:nodejs /workspace/hollis-identity/node_modules ./node_modules
COPY --from=build --chown=identity:nodejs /workspace/hollis-identity/dist ./dist
COPY --from=build --chown=identity:nodejs /workspace/hollis-identity/prisma ./prisma
COPY --chown=identity:nodejs prisma.config.ts ./
COPY --chown=identity:nodejs package.json ./

USER identity

EXPOSE 4001

# Liveness probe — Node's global fetch avoids busybox wget flag quirks. ECS does
# not read this (the task definition has no containerHealthCheck; the ALB target
# group polls /health), but it makes `docker run` locally self-describing.
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:4001/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

# Apply committed migrations before accepting traffic. Prisma serializes
# concurrent migrate-deploy invocations, so a rolling ECS deployment with two
# tasks remains safe and the schema is authoritative before app startup.
#
# The local binary is invoked directly rather than through `npx`: npx wants a
# writable npm cache and would resolve through the network on a cache miss,
# neither of which is appropriate in a non-root runtime container.
CMD ["sh", "-c", "./node_modules/.bin/prisma migrate deploy && exec node dist/index.js"]
